### ISSUE TITLE
When updating using the old project format Pros creates a new main.cpp file.

### ISSUE THREAD

**Issue by lerker100** [purduesigbots/pros#263] opened 2020-11-06 16:41 UTC
#### Expected Behavior:
Not to create the main.cpp file. This breaks users code if they aren't using that project structure.

#### Actual Behavior:
After updating to a new version of Pros. A new main.cpp file is created. This breaks users code. By causing multiple variable declarations.

#### Steps to reproduce:
Make a pros project with an older version of Pros.
Move opcontrol and autonomous functions to different file. (Like how Pros used to do it.)
Then run 'prosv5 c u'
Now try to compile it 'prosv5 make all'

#### System information:
Platform: V5
PROS Kernel Version:
```
Name      Version    Origin
--------  ---------  -------------
kernel    3.3.1      pros-mainline
okapilib  4.0.5      pros-mainline
```

CLI output for those commands.
```
[user@PBP 2020-2021]$ prosv5 c u
Upgrading kernel
Updating pros-mainline... Done
Downloading kernel@3.3.1 [####################################] 100%            
Extracting kernel@3.3.1 [####################################] 100%
Fetched kernel@3.3.1 from pros-mainline depot
Adding kernel@3.3.1 to registry...Done
Applying kernel@3.3.1 [####################################] 100%
Finished applying kernel@3.3.1 to /home/user/Git/2020-2021
Upgrading okapilib
Applying okapilib@4.0.5 [####################################] 100%
Finished applying okapilib@4.0.5 to /home/user/Git/2020-2021
[user@PBP 2020-2021]$ prosv5 make
Creating cold package with libc,libm,libpros,okapilib [OK]
Stripping cold package  [DONE]
Section sizes:
   text    data     bss   total     hex filename
1.05MB  4.34KB  47.62MB  48.67MB 30aa5ab bin/cold.package.elf
Compiled src/Chassis.cpp [OK]
Compiled src/Screen.cpp [OK]
Compiled src/autonomous.cpp [OK]
Compiled src/initialize.cpp [OK]
Compiled src/main.cpp [OK]
Compiled src/opcontrol.cpp [OK]
Adding timestamp [OK]
Linking hot project with ./bin/cold.package.elf and libc,libm,libpros,okapilib [ERRORS]
/usr/lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: bin/main.cpp.o: in function `disabled':
main.cpp:(.text.disabled+0x0): multiple definition of `disabled'; bin/initialize.cpp.o:/usr/arm-none-eabi/include/c++/10.2.0/bits/unique_ptr.h:962: first defined here
/usr/lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: bin/main.cpp.o: in function `competition_initialize':
main.cpp:(.text.competition_initialize+0x0): multiple definition of `competition_initialize'; bin/initialize.cpp.o:/usr/arm-none-eabi/include/c++/10.2.0/bits/shared_ptr_base.h:547: first defined here
/usr/lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: bin/main.cpp.o: in function `autonomous':
/home/user/Git/2020-2021/./include/okapi/api/util/logging.hpp:183: multiple definition of `autonomous'; bin/autonomous.cpp.o:/usr/arm-none-eabi/include/c++/10.2.0/bits/shared_ptr_base.h:1183: first defined here
/usr/lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: bin/main.cpp.o: in function `initialize':
/home/user/Git/2020-2021/src/main.cpp:25: multiple definition of `initialize'; bin/initialize.cpp.o:/home/user/Git/2020-2021/./include/okapi/api/util/logging.hpp:178: first defined here
/usr/lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: bin/opcontrol.cpp.o: in function `opcontrol':
/home/user/Git/2020-2021/src/opcontrol.cpp:18: multiple definition of `opcontrol'; bin/main.cpp.o:/home/user/Git/2020-2021/src/main.cpp:76: first defined here
collect2: error: ld returned 1 exit status
make: *** [common.mk:239: bin/hot.package.elf] Error 1
Error: Failed to build
```

**Comment by nathan-moore** [comment] 2020-11-06 17:50
duplicate of https://github.com/purduesigbots/pros-cli/issues/131

**Closed by nathan-moore** 2020-11-06 17:50 UTC
