### ISSUE TITLE
File I/O works with C functions but not with C++ std::fstream

### ISSUE THREAD

**Issue by 3038922** [purduesigbots/pros#88] opened 2018-11-13 02:32 UTC
#### Expected Behavior:
Using STL to read and write files
#### Actual Behavior:
1 if i use "std::fstream" ,file can't open
2 If I use C language, I can open and read files. But if there are Chinese characters, PYTHON3 will make mistakes. Maybe it's the encoding of files.
3 If I set my configRead class as a global class, it will not read correctly, because the global class construction is disorderly, and it only works after initialize (). Because there is no parametric constructor for pros::Motor class, all of my robot project classes can only be constructed as local variables.
#### System information:
Operating System:  (Windows, OS X, Ubuntu)
windows 10 1803
PROS Version: (run `pros --version`)
pros, version 3.1.2
#### Additional Information
kernel 3.3.4
oklib 3.3.7
#### Screenshots/Output Dumps/Stack Traces
![1](https://user-images.githubusercontent.com/33926386/48387118-62b04b00-e72f-11e8-8c9f-8f14c0cc603e.png)
<img width="719" alt="2" src="https://user-images.githubusercontent.com/33926386/48387100-53c99880-e72f-11e8-86d3-beb08aff8cc7.png">

**Comment by HotelCalifornia** [comment] 2019-03-11 01:31
It seems that the problem is specifically with input streams (`std::ifstream`). Output streams work, but they will only flush when closed (either explicitly or when the dtor is called)

**Comment by HotelCalifornia** [comment] 2019-09-02 23:52
closed by #112

**Closed by HotelCalifornia** 2019-09-02 23:52 UTC
Labels: bug, p: normal, workaround available
