### ISSUE TITLE
🐛[BUG] - `Imu::is_calibrating` returns `true` if imu is not connected

### ISSUE THREAD

**Issue by SizzinSeal** [purduesigbots/pros#626] opened 2024-01-19 00:37 UTC
**Describe the bug**
`Imu::is_calibrating` returns `true` if imu is not connected

**To Reproduce**
1. Instantiate an IMU on a port where it is not connected
2. call `Imu::is_calibrating()`

**Expected behavior**
It should return `false`

**Screenshots**

**Desktop (please complete the following information):**
 - PROS 3.8.0

**Comment by WillXuCodes** [comment] 2024-02-04 00:06
Closed by #628

**Comment by WillXuCodes** [comment] 2024-02-04 04:00
Not closing this yet due to #628 not being merged yet.

**Comment by liam-teale** [comment] 2024-04-02 01:55
Reproduced in kernel version 3.8.3

**Closed** 2024-04-03 18:31 UTC
Labels: bug
