### ISSUE TITLE
Disconnection of controller

### ISSUE THREAD

**Issue by Eden4897** [purduesigbots/pros#192] opened 2020-01-02 20:05 UTC
#### Expected Behavior:
It is not supposed to disconnect.

#### Actual Behavior:
After loading a program to the controller, it disconnects at the 11th second

#### Steps to reproduce:
Download a program to the controller (wirelessly) and keep the usb wire connected. Also plug in a competition switch (i am not sure if that is needed).

#### System information:
Platform: V5
PROS Kernel Version: 3.2.0

**Comment by nathan-moore** [comment] 2020-01-02 21:41
This seems to be a duplicate of https://github.com/purduesigbots/pros-cli/issues/112.

**Closed by nathan-moore** 2020-01-02 21:41 UTC
