### ISSUE TITLE
pros-editor doesn't create desktop entry

### ISSUE THREAD

**Issue by GLMONTER** [purduesigbots/pros#80] opened 2018-11-10 06:35 UTC
#### Expected Behavior:
For the pros-editor.deb to make a shortcut

#### Actual Behavior:
doesn't make a shortcut

#### Steps to reproduce:
just install the .deb file

#### System information:
Ubuntu 18.10, this happens on any Ubuntu version
Kernel Version: 4.18.0-10

#### Additional Information
When you install the pros-editor.deb, it doesn't produce a application shortcut like most programs do.

**Comment by HotelCalifornia** [comment] 2018-12-20 16:52
actually, i'm going to close this as a duplicate of #63

**Closed by HotelCalifornia** 2018-12-20 16:52 UTC
Labels: Platform: *nix, Priority: Low, Project: Installers
